inherit_gem:
    rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - "/config/**/*"

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/ClassMethodsDefinitions:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes